import { FormEvent, useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Alert, Box, Button, Card, CardContent, Checkbox, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, FormControlLabel, FormGroup, InputLabel, MenuItem, Select, Stack, TextField, Typography } from '@mui/material'
import ArrowBack from '@mui/icons-material/ArrowBack'
import Download from '@mui/icons-material/Download'
import { api, errorMessage } from '../api'
import type { Credential, Door, Permission, Schedule, UserRecord, UserRole } from '../types'

const days = ['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY']
const currentYangonDay = () => new Intl.DateTimeFormat('en-US',{weekday:'long',timeZone:'Asia/Yangon'}).format(new Date()).toUpperCase()
const defaultExpiry = () => { const date = new Date(Date.now() + 10*24*60*60*1000); date.setMinutes(date.getMinutes()-date.getTimezoneOffset()); return date.toISOString().slice(0,16) }

export default function UserDetailPage() {
  const { id = '' } = useParams(), navigate = useNavigate()
  const [user,setUser]=useState<UserRecord>(), [doors,setDoors]=useState<Door[]>([]), [permissions,setPermissions]=useState<Permission[]>([]), [schedules,setSchedules]=useState<Schedule[]>([]), [credentials,setCredentials]=useState<Credential[]>([])
  const [error,setError]=useState(''), [selectedDays,setSelectedDays]=useState<string[]>([currentYangonDay()]), [startTime,setStartTime]=useState('08:00'), [endTime,setEndTime]=useState('18:00')
  const [expiry,setExpiry]=useState(defaultExpiry()), [usageMode,setUsageMode]=useState<'ONE_TIME'|'MULTI_USE'>('MULTI_USE'), [maxUses,setMaxUses]=useState(''), [issued,setIssued]=useState<Credential>(), [qrOpen,setQrOpen]=useState(false)
  const [editOpen,setEditOpen]=useState(false), [edit,setEdit]=useState({publicId:'',fullName:'',email:'',phone:'',role:'STAFF' as UserRole})
  const load=()=>Promise.all([api.get<UserRecord>(`/api/users/${id}`),api.get<Door[]>('/api/doors'),api.get<Permission[]>(`/api/users/${id}/permissions`),api.get<Schedule[]>(`/api/users/${id}/schedules`),api.get<Credential[]>(`/api/users/${id}/qr-credentials`)]).then(([u,d,p,s,c])=>{setUser(u.data);setEdit({publicId:u.data.publicId,fullName:u.data.fullName,email:u.data.email||'',phone:u.data.phone||'',role:u.data.role});setDoors(d.data);setPermissions(p.data);setSchedules(s.data);setSelectedDays(s.data.length?[...new Set<string>(s.data.map(x=>x.dayOfWeek))]:[currentYangonDay()]);if(s.data.length){setStartTime(s.data[0].startTime.slice(0,5));setEndTime(s.data[0].endTime.slice(0,5))}setCredentials(c.data)}).catch(e=>setError(errorMessage(e)))
  useEffect(()=>{void load()},[id])
  const permittedIds=useMemo(()=>new Set(permissions.map(p=>p.doorId)),[permissions])
  const toggleDoor=async(doorId:string)=>{const next=permittedIds.has(doorId)?[...permittedIds].filter(x=>x!==doorId):[...permittedIds,doorId];try{const r=await api.put(`/api/users/${id}/permissions`,{doorIds:next});setPermissions(r.data)}catch(e){setError(errorMessage(e))}}
  const saveSchedule=async()=>{try{const r=await api.put(`/api/users/${id}/schedules`,{schedules:selectedDays.map(dayOfWeek=>({dayOfWeek,startTime,endTime}))});setSchedules(r.data)}catch(e){setError(errorMessage(e))}}
  const toggleStatus=async()=>{if(!user)return;try{const r=await api.patch(`/api/users/${id}/status`,{status:user.status==='ACTIVE'?'INACTIVE':'ACTIVE'});setUser(r.data)}catch(e){setError(errorMessage(e))}}
  const saveProfile=async(event:FormEvent)=>{event.preventDefault();try{const r=await api.patch(`/api/users/${id}`,edit);setUser(r.data);setEditOpen(false)}catch(e){setError(errorMessage(e))}}
  const createQr=async(event?:FormEvent, regenerateId?:string)=>{event?.preventDefault();try{const payload={expiresAt:new Date(expiry).toISOString(),usageMode,maxUses:maxUses?Number(maxUses):null};const url=regenerateId?`/api/qr-credentials/${regenerateId}/regenerate`:`/api/users/${id}/qr-credentials`;const r=await api.post(url,payload);setIssued(r.data);setQrOpen(true);load()}catch(e){setError(errorMessage(e))}}
  const revoke=async(credentialId:string)=>{try{await api.post(`/api/qr-credentials/${credentialId}/revoke`);load()}catch(e){setError(errorMessage(e))}}
  const download=()=>{if(!issued?.qrDataUrl)return;const a=document.createElement('a');a.href=issued.qrDataUrl;a.download=`smartdoor-${user?.publicId||'credential'}.png`;a.click()}
  if(!user)return <Typography>Loading user…</Typography>
  return <Stack spacing={3}>
    <Button startIcon={<ArrowBack/>} onClick={()=>navigate('/users')} sx={{alignSelf:'flex-start'}}>Back to users</Button>
    <Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><div><Typography variant="h4" fontWeight={800}>{user.fullName}</Typography><Typography color="text.secondary">{user.publicId} · {user.role}</Typography></div><Stack direction="row" spacing={1}><Button variant="outlined" onClick={()=>setEditOpen(true)}>Edit user</Button><Button color={user.status==='ACTIVE'?'warning':'success'} variant="outlined" onClick={toggleStatus}>{user.status==='ACTIVE'?'Deactivate user':'Activate user'}</Button></Stack></Stack>
    {error&&<Alert severity="error" onClose={()=>setError('')}>{error}</Alert>}
    <Card><CardContent><Typography variant="h6" fontWeight={750}>Door permissions</Typography><Typography color="text.secondary" mb={1}>Select the doors this user may enter.</Typography><FormGroup>{doors.map(door=><FormControlLabel key={door.id} control={<Checkbox checked={permittedIds.has(door.id)} onChange={()=>toggleDoor(door.id)}/>} label={`${door.name} (${door.publicId})`}/>)}</FormGroup></CardContent></Card>
    <Card><CardContent><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" alignItems={{sm:'center'}} gap={1}><div><Typography variant="h6" fontWeight={750}>Access schedule</Typography><Typography color="text.secondary">Times use Asia/Yangon local time.</Typography></div><Button size="small" variant="outlined" onClick={()=>setSelectedDays([currentYangonDay()])}>Select today</Button></Stack><FormGroup row sx={{my:1}}>{days.map(day=><FormControlLabel key={day} control={<Checkbox checked={selectedDays.includes(day)} onChange={()=>setSelectedDays(selectedDays.includes(day)?selectedDays.filter(d=>d!==day):[...selectedDays,day])}/>} label={day.slice(0,3)}/>)}</FormGroup><Stack direction={{xs:'column',sm:'row'}} spacing={2}><TextField label="Start" type="time" value={startTime} onChange={e=>setStartTime(e.target.value)} InputLabelProps={{shrink:true}}/><TextField label="End" type="time" value={endTime} onChange={e=>setEndTime(e.target.value)} InputLabelProps={{shrink:true}}/><Button variant="contained" onClick={saveSchedule}>Save schedule</Button></Stack><Typography variant="body2" color="text.secondary" mt={1}>{schedules.length} active schedule rows</Typography></CardContent></Card>
    <Card><CardContent><Typography variant="h6" fontWeight={750}>Issue QR credential</Typography><Stack component="form" onSubmit={e=>createQr(e)} direction={{xs:'column',md:'row'}} spacing={2} mt={2}><TextField label="Expires" type="datetime-local" value={expiry} onChange={e=>setExpiry(e.target.value)} InputLabelProps={{shrink:true}} required/><FormControl sx={{minWidth:160}}><InputLabel>Usage</InputLabel><Select label="Usage" value={usageMode} onChange={e=>setUsageMode(e.target.value as typeof usageMode)}><MenuItem value="MULTI_USE">Multi-use</MenuItem><MenuItem value="ONE_TIME">One-time</MenuItem></Select></FormControl>{usageMode==='MULTI_USE'&&<TextField label="Maximum uses (optional)" type="number" value={maxUses} onChange={e=>setMaxUses(e.target.value)} inputProps={{min:1}}/>}<Button type="submit" variant="contained">Generate QR</Button></Stack>
      <Stack spacing={1.2} mt={3}>{credentials.map(c=><Stack key={c.id} direction={{xs:'column',md:'row'}} justifyContent="space-between" alignItems={{md:'center'}} gap={1} p={1.5} sx={{border:'1px solid #e2e8f0',borderRadius:2}}><div><Stack direction="row" gap={1} alignItems="center"><Chip size="small" color={c.status==='ACTIVE'?'success':'default'} label={c.status}/><Typography fontWeight={650}>{c.usageMode.replace('_',' ')}</Typography></Stack><Typography variant="body2" color="text.secondary">Expires {new Date(c.expiresAt).toLocaleString()} · Used {c.usageCount}{c.maxUses?`/${c.maxUses}`:''}</Typography></div>{c.status==='ACTIVE'&&<Stack direction="row"><Button color="warning" onClick={()=>revoke(c.id)}>Revoke</Button><Button onClick={()=>createQr(undefined,c.id)}>Regenerate</Button></Stack>}</Stack>)}</Stack>
    </CardContent></Card>
    <Dialog open={qrOpen} onClose={()=>setQrOpen(false)} fullWidth maxWidth="xs"><DialogTitle>QR credential created</DialogTitle><DialogContent><Stack alignItems="center" spacing={2}><Typography color="text.secondary">This QR is shown only when issued. Download or print it now.</Typography>{issued?.qrDataUrl&&<Box component="img" src={issued.qrDataUrl} alt="Issued SmartDoor QR code" sx={{width:'100%',maxWidth:360}}/>}</Stack></DialogContent><DialogActions><Button onClick={download} startIcon={<Download/>}>Download PNG</Button><Button variant="contained" onClick={()=>window.print()}>Print</Button><Button onClick={()=>setQrOpen(false)}>Close</Button></DialogActions></Dialog>
    <Dialog open={editOpen} onClose={()=>setEditOpen(false)} fullWidth maxWidth="sm"><Stack component="form" onSubmit={saveProfile}><DialogTitle>Edit user</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField label="User ID" required value={edit.publicId} onChange={e=>setEdit({...edit,publicId:e.target.value})}/><TextField label="Full name" required value={edit.fullName} onChange={e=>setEdit({...edit,fullName:e.target.value})}/><TextField label="Email" type="email" value={edit.email} onChange={e=>setEdit({...edit,email:e.target.value})}/><TextField label="Phone" value={edit.phone} onChange={e=>setEdit({...edit,phone:e.target.value})}/><FormControl><InputLabel>Role</InputLabel><Select label="Role" value={edit.role} onChange={e=>setEdit({...edit,role:e.target.value as UserRole})}><MenuItem value="ADMIN">Admin user</MenuItem><MenuItem value="STAFF">Staff</MenuItem><MenuItem value="VISITOR">Visitor</MenuItem></Select></FormControl></Stack></DialogContent><DialogActions><Button onClick={()=>setEditOpen(false)}>Cancel</Button><Button type="submit" variant="contained">Save changes</Button></DialogActions></Stack></Dialog>
  </Stack>
}
